# Site settings
title: Club de Robótica-Mecatrónica
email: crm-uam@googlegroups.com
description: "Web del Club de Robótica y Mecatrónica (CRM) de la Escuela Politécnica Superior de la Universidad Autónoma de Madrid"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://crm-uam.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from

permalink: /blog/:year/:month/:day/:title.html

